quarkus:

  http:
    cors: true

  hibernate-orm:
    database:
      generation: drop-and-create

  datasource:
    db-kind: mysql
    username: root
    password: root
    jdbc:
      url: jdbc:mysql://localhost:3308/bigfods

  smallrye-jwt:
    enabled: true

mp:
  jwt:
    verify:
      publickey:
        location: publicKey.pem
      issuer: "http://localhost:8080/api/login"

smallrye:
  jwt:
    sign:
      key: privateKey.pem


