quarkus:

  http:
    cors: true

  hibernate-orm:
    database:
      generation: drop-and-create

  datasource:
    db-kind: mysql
    username: root
    password: root
    jdbc:
      url: jdbc:mysql://localhost:3308/bigfods

mp:
  jwt:
    verify:
      publicKey: publicKey.pem
      issuer:

smallrye:
  jwt:
    sign:
      key:
        location: privateKey.pem


